### ISSUE TITLE
Issues with rankNet and merged cellchat object 

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#123]
Hi @sqjin 

I have two questions 

First one is on rankNet function. Is there a specific order to the pathways that are displayed? For example, Pathways that are unique to dataset1 in red , then pathways that are equally important in both the datasets in black in the middle followed by pathways that are unique to the dataset2 in green at the end? I re-installed the latest version this morning. I notice that some pathways that are in black text comes in between the red text. Please see the snapshot of the top portion of figure below. 

This is the code I use
`rankNet(cellchat.merged, mode = "comparison", stacked = T)`

![image](https://user-images.githubusercontent.com/68548237/104881460-3caf1280-5959-11eb-8414-8004f43140e3.png)

Second question is on  `netVisual_diffInteraction`. When I use this code on the merged object `netVisual_diffInteraction(cellchat.merged, weight.scale = T, measure = "count.merged", label.edge = T)`
I receive the following error message 
```
Error in if (nrow(adjmatrix) != ncol(adjmatrix)) { : 
  argument is of length zero
```
Also, when I just type the object that is merged on the console `cellchat.merged` I receive this error. 
```
Error in (new("standardGeneric", .Data = function (object)  : 
  object 'cellchat' not found
```

It would be really great, if you could advise on this and how to check if the cellchat object is properly merged. The other functions on comparing two datasets seems to work without any issues. 

Thanks a lot

**Comment by sqjin** [comment]
@jv-20 Your understanding on how we rank the pathways is correct. We now add an option to perform statistical test, and thus you see more black text. Please see the documentation. 

I am sorry I have no idea on the error in netVisual_diffInteraction. please run the sources codes to figure out the reason. 

'object 'cellchat' not found': This issue is now fixed.

**Comment by jv-20** [comment]
Hi @sqjin , Many thanks for the reply and the information. 

The issue associated with rankNet pathway figure is resolved. I was wondering if it is possible to get the p.value associated with the statistical test in the results table. I am using `return.data=T` to get the table and using the following code, but I don't see the p-value column. Please advise.
```
res.ranknet=rankNet(cellchat.merged, mode = "comparison", stacked = T,return.data = T)
df=res.ranknet$signaling.contribution
```

Another issue I am having is with `rankSimilarity` function `rankSimilarity(cellchat.merged, type = "functional")`. I receive the following error message when running this function.

```
Compute the distance of signaling networks between datasets 1 2 
Error in methods::slot(object, slot.name)$similarity[[type]]$matrix[[comparison.name]] : 
  subscript out of bounds

```
It would be great if you could comment on this. Thank you in advance

**Comment by sqjin** [comment]
@jv-20 You should re-run all the functions related with the functional similar analysis.  You should set ``do.stat = TRUE

**Comment by jv-20** [comment]
Thank you @sqjin. I re-run the functions and is sorted. Many thanks for the quick response.

**Comment by gt7901b** [comment]
Hi, @sqjin 

Please help me to better understand the rankNet relative information flow stacked barplot. The MHC1 pathways have similar contribution.scaled in "information flow" barplot, so the label is black which means equal. But in stacked barplot, SampleA has majority of the bar, does it mean in sampleA, MHC-I is contribute more to the overall information flow than MHC-I to sampleB?
The total information flow in sampleA is 1.668, sampleB is 0.456. But 1.4/1.668 not equal 0.69. Is my interpretation wrong? 


name	                  contribution	       contribution.scaled	group	contribution.relative.1	pvalues
MHC-I	MHC-I	 1.409976e+00.    0.69034055	              SampleA	0.1	                               9.814319e-01
MHC-I1	MHC-I	2.032301e-01	0.62758231	              SampleB	0.1	                               9.814319e-01

thanks for your time

**Comment by sqjin** [comment]
@gt7901b Hi, the result from the stacked barplot is correct, i.e., MHC-I is contribute more to the overall information flow in sampleA than sampleB.  To show the information flow in the normal bar plot (not stacked), we scale the contribution value so that you can see the pathways with very small contribution values, which might be also important because signaling networks with less interactions tend to have small contribution values.  However, the issue you see here is caused by such scale operation. For your case, the scaled MHC in sampleA becomes similar to the value in sampleB, which is not totally correct based on the specific values you shown.  I have to think about how to do a scale operation in a better way.

**Comment by gt7901b** [comment]
got it. thank you so much.
