### ISSUE TITLE
How to choose false or true for raw use in computeCommunProb.?

### ISSUE THREAD

**Issue by zenghh1226** [sqjin/CellChat#133]
Thank you for developing such a friendly and useful tool. I have some questions:
1. How to choose false or true for raw use in computeCommunProb.?  How to define shallow sequencing depth? Does deep sequencing depth mean the data from platforms like smart seq？ Could you provide a cutoff for sequencing depth,like genes per cell or reads per cell? 
2.What dose nboot= 100 in computeCommunProb. means？ 
3.Does  Log Fold Change mean log10 Fold Change?
4. How to explain the that the strenght of interaction is not consistence with gene expression level?
5. In the new version of cellchat, cellchat could give the result of increase or decrease LRs between groups, is there a p-value?

**Comment by sqjin** [comment]
@zenghh1226 There is no good answer on how to define the shallow sequencing depth. This questions is more like whether you want to do imputation when analyzing the data.  In practice,  I think you can consider not to use the raw data if you find some particular ligands/receptor expression of interest are rarely captured. If you believe your data is in a good quality, for example based on your clustering analysis, you can just use the raw data to perform cell communication analysis. 

nboot is used to compute a pvalue from a permutation test. 

Log Fold Change is natural logarithm

The interaction strength can also be affected by the co-factors such as agonist/antagonist.  I hope this is not caused by setting raw.use = FALSE. 

There is no pvalue for the increase or decrease analysis.  Are you talking about the 'netVisual_diffInteraction'?

**Comment by zenghh1226** [comment]
Thanks for kind reply.  I meant to know whether there is p_value in the Part3, but I also curious about netVisual_diffInteraction. So there is no pvalue for the increase or decrease analysis in the comparison anaylsis between dataset?
#Part III: Identify the upgulated and down-regulated signaling ligand-receptor pairs
netVisual_bubble(cellchat, comparison = c(1, 2), sources.use = c(2), targets.use = c(1:15),angle.x = 45)

**Comment by sqjin** [comment]
@zenghh1226 In both netVisual_diffInteraction and netVisual_bubble, this is no pvalue when determining the increased or decreased signals.  You may can check the Part III in the updated tutorial, where we provide another option to do it based on the differential expression analysis.
