### ISSUE TITLE
Confused on preprocessing for cellchat comparisons between multiple datasets

### ISSUE THREAD

**Issue by cswoboda** [sqjin/CellChat#159]
Hello!

Thanks again so much for this tool, it's really great. I have 4 replicates for condition A, and 3 replicated for condition B. Each were sequenced separately. I essentially want to just compare conditions A and B. Do I run cellchat on each object seperately, or run it on an integrated object of just one sample?

For example, the tutorial code is below:
cellchat.NL <- readRDS(url("https://ndownloader.figshare.com/files/25954199"))
cellchat.LS <- readRDS(url("https://ndownloader.figshare.com/files/25956518"))
object.list <- list(NL = cellchat.NL, LS = cellchat.LS)
cellchat <- mergeCellChat(object.list, add.names = names(object.list))

Now, here's two ways I could preprocess the data:

object.list <- list(Disease = cellchat_disease, Control = cellchat_control)
where cellchat_disease is an integrated object corrected by harmony

or

object.list <- list(Disease = c(sample1, sample2, sample3), Control = c(sample4, sample5, sample6))
where sample1-6 represent individual seurat objects which have been run through cellchat.

Which would be best in your eyes?

Thanks,

Casey

**Comment by sqjin** [comment]
@cswoboda Since you have multiple biological replicates, I suggest to run cellchat for the aggregated data (combining all data together from replicates) of each condition. Thus, you will only have two cellchat objects (each for one condition), and then merge them for comparison analysis.

**Comment by cswoboda** [comment]
Thanks! Would best practices be creating a single integrated object to control for batch effect across all samples and then split that object into the control and treatment populations do you think? Or is that unnecessary for the level at which cellchat computes interactions?

**Comment by sqjin** [comment]
@cswoboda To run CellChat's comparison analysis, one needs to first create a single cellchat object for each condition and then merge them for comparison analysis. For the batch effect's concern in single cell analysis, if you have batch corrected data that can be used as input of CellChat, it will be nice since CellChat's analysis is based on the expression level of ligands and receptors. However, to my knowledge, most of tools do not generate batch corrected data that can be used for downstream analysis such as differential expression analysis.

**Comment by cswoboda** [comment]
Thank you! Apologies one more question before I close this out. You mention in the documentation of computecommunprob that:

"whether consider the proportion of cells in each group across all sequenced cells. Set population.size = FALSE if analyzing sorting-enriched single cells, to remove the potential artifact of population size. Set population.size = TRUE if analyzing unsorted single-cell transcriptomes, with the reason that abundant cell populations tend to send collectively stronger signals than the rare cell populations."

So, my tissue is unsorted, however, there's one celltype that is way overly abundant compared to the rest. Is it wrong to set population size to false here, if I want to highlight the interactions between the other smaller celltypes where I have evidence to suggest they are playing a crucial role in signaling within this dataset?

Thanks,

Casey

**Comment by YOU-k** [comment]
Hi, I am stuck at the step to generate batch-corrected count matrix as well.
I have one group of cells with multiple batches. The cell type cells I would like to run the analysis are abundant in different batches. Is there any suggestion for me?
Cheers,
Yue

**Comment by sqjin** [comment]
Hi @YOU-k , currently I do not have a better suggestion on the generation of batch-corrected count matrix. Generally, we simply merge the data matrix from different batches and use normalization methods such as in Seurat to obtain a data matrix as input of cellchat.

**Comment by YOU-k** [comment]
OK. Thanks for the suggestion!

**Comment by kaqisekuzi** [comment]
Hi @sqjin , Now I have the same problem：
Q1,  For three biological replicates under the same conditions, do I need to use the [Integration](https://satijalab.org/seurat/articles/integration_introduction.html) method to remove batch effects?  Or, a simple [merge](https://satijalab.org/seurat/articles/merge_vignette.html) will do?

Q2,  For the same sample of the same conditions, there are two sequencing data (because the number of cells is too large), it is recommended to use the merge method mentioned in Q1 or the Integration method？

Q3,  If I use Integration, I encountered the following error when creating the cellchat object. I checked and found that my RNA does not have var.features. Do I need to specify assays as Integration? Are there any requirements for assays (RNA or integrated?)
my code:

> before <- subset(pbmc, subset = group == "before")
after <- subset(pbmc, subset = group == "after")
cellchat.before <- updateCellChat(before)
cellchat.after <- updateCellChat(after)
object.list <- list(before = cellchat.before, after = cellchat.after)
cellchat <- mergeCellChat(object.list, add.names = names(object.list))

Error
![image](https://github.com/sqjin/CellChat/assets/59284758/5ea10cfb-e5d4-4d21-98d9-c43d5d761c5f)

@assays$RNA
![image](https://github.com/sqjin/CellChat/assets/59284758/069fd190-fbc3-469d-afd3-d24ce2e6e942)
@assays$integrated
![image](https://github.com/sqjin/CellChat/assets/59284758/5da437e5-7729-41d6-9cd3-a8744530fe5d)

**Comment by Ver-Luca** [comment]
@kaqisekuzi According to Seurat, you shouldn't run `FindVariableFeatures()` on the _integrated_ assay but on the **RNA** assay
