### ISSUE TITLE
Adding cofactor information for customized database

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#197]
Hi @sqjin 

I am trying to use a customized database of interactions. I would like to add cofactor and complex information. 

I am just trying to get the rules correct.

1.Which column does the rows of cofactor table refer to in the interaction file? 
2.Does the cofactors have to be grouped by pathways or is it okay to refer by individual ligand/receptor name?
3.The rownames of complex file refers to ligands/receptors in the interaction file isn't it?

Thank you in advance

**Comment by sqjin** [comment]
@jv-20 The cofactor includes the columns named agonist | antagonist | co_A_receptor | co_I_receptor

No. The cofactor is associated with each l-r pair. 

Yes, rownames of complex file refers to ligands/receptors in the interaction file . 

May I ask why you use a customized database? Is it because of missing L-R pairs in CellChatDB or the case where CellChat does not predict certain expected signaling interactions.

**Comment by jv-20** [comment]
Hi @sqjin, thanks for the reply. 

For your question `May I ask why you use a customized database? Is it because of missing L-R pairs in CellChatDB or the case where CellChat does not predict certain expected signaling interactions.`

Yes it is because of missing L-R pairs in CellChatDB. I want to use the recently compiled OmnipathR L-R interactions and their co-factors and run cellchat. In my experience, cellchat is quite robust in predicting interactions. Thank you for this amazing package. 

Basically, I am trying to create a co-factor table from Omnipath information. Please have a look at https://github.com/saezlab/OmnipathR/issues/28 and https://github.com/saezlab/OmnipathR/issues/30

I have couple questions on creating the co-factor table that is suitable for running cellchat. It is a bit unclear to me about the rownames of the co-factor table. The following image shows a screenshot of the co-factor table from cellchat database. The rownames that you have in the co-factor table for example the first one `ACTIVIN anatagonist FST `  here FST is the ligand and members of ACTIVIN pathway are antagonist to FST. Is this correct? 

![Q1_COFA_cellchat](https://user-images.githubusercontent.com/68548237/118048443-33b4d780-b374-11eb-9941-31f340d45a0e.PNG)

My question is about row names when creating a customized co-factor table. Instead of referencing by pathway name in the row names of the co-factor table, could I have individual L-R pairs associated with the pathway names appended by text "antagonist" to FST like shown below? Would this affect the analysis and inference?

![image](https://user-images.githubusercontent.com/68548237/118050065-927b5080-b376-11eb-99a6-5b28f6645676.png)

It would be really helpful, if you could give some advice on the rules or tutorial for making customized co-factor table. 

Thanks in advance,
Janaki

**Comment by sqjin** [comment]
@jv-20 You can define the rownames using any string you want, but you need to make sure that you use the same string in the 'interaction_input' file because this is the 'key word' for matching the information from these two tables.  

If the ligand-receptor pair has ACTIVIN anatagonist in the 'interaction_input' file, then FST is the anatagonist of this ligand-receptor pair. 

If there is no direction, I suggest to remove such cofactors.

**Comment by jv-20** [comment]
Okay thank you @sqjin. My query is resolved. Thanks
