### ISSUE TITLE
no x lab when using netVisual_bubble()

### ISSUE THREAD

**Issue by futmoon** [sqjin/CellChat#206]
when I use netVisual_bubble, there is no x lab in the picture. how to fix it?
<img width="574" alt="1" src="https://user-images.githubusercontent.com/55536174/119282797-8e500c80-bc6d-11eb-856f-c81b3994ceaa.PNG">

**Comment by sqjin** [comment]
@futmoon This is interesting. Could you please share my the data to replicate your error/

**Comment by futmoon** [comment]
it is solved:). it turns out to be caused by "(" ")" in cellchat@idents.

**Comment by flde** [comment]
Hi @sqjin, I have the same issue when with color.text.use=TRUE (left). My cell names do contain whitespace and breakets. Is there anyway we could fix that issue since re-naming all cells would be quite some work. 
![download](https://user-images.githubusercontent.com/20926246/197173706-057466a4-af45-4c73-81e0-330f115de8e0.png)

**Comment by nandini0910** [comment]
Hi! I'm getting an error similar to this. Instead of having different labels for the y-axis, I'm only getting one label- "NA". How do I fix this?
![0000af](https://user-images.githubusercontent.com/60441159/223584997-20424c31-00c5-4506-a730-3432cb5389dc.png)
