### ISSUE TITLE
Pvalue correction

### ISSUE THREAD

**Issue by MariaRosariaNucera** [sqjin/CellChat#218]
Hello,
First of all I would like to thank you for the useful tool :) 
I was wondering which correction method did you use to adjust the pvalue when calculating overexpressed genes with the function "identifyOverExpressedGenes".
I tried calculating the differential expressed genes in my dataset using Scanpy function "scanpy.tl.rank_genes_groups" with Bonferroni correction but I am unable to find most of the ligand or receptors that are listed as significant by CellChat so I suppose that maybe the reason can be found in the different correction method.
Thank you in advance :)

**Comment by sqjin** [comment]
@MariaRosariaNucera Currently CellChat did not use any correction method after computing the p-values. One of the reason is that we did not want to filter out two many ligands receptors at this initial step.  But I can also add the `bonferroni` correction as an option. 

You can also use your own HVGs by setting `object@var.features[["features"]] <- features.sig`

**Comment by MariaRosariaNucera** [comment]
Thank you! If you could add this option it would be great :)
At which step of the analysis would be better to assign the var.features?

**Comment by sqjin** [comment]
@MariaRosariaNucera Instead of running this function, you can directly assign this list of genes.

**Comment by MariaRosariaNucera** [comment]
Ok I got it, thank you :)
