### ISSUE TITLE
netVisual_heatmap() does not scale/normalize data for comparison of different datasets

### ISSUE THREAD

**Issue by ManuelMoradiellos** [sqjin/CellChat#475]
Hi!

I was using the package to do a comparison of some specific pathways within my dataset of three conditions following the examples done at the comparison [tutorial](https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/tutorial/Comparison_analysis_of_multiple_datasets.html).

First, to get a general overview I used `netVisual_aggregate()` within a loop and to better compare the three results I made sure to correctly use `edge.weight.max` argument. The results looked something like this:

![CCL_allcells_circleplot](https://user-images.githubusercontent.com/53752249/189384020-69c18daf-8435-4c16-8ea0-6f49c2fcb206.png)

As you can see, the "Low" condition had lower strength in the Macrophages autocrine signaling than the other two.

To get a better look at these trends I used `netVisual_heatmap()` as mentioned in the fourth part of the comparison tutorial. This function doesn't include any way to scale or account for maximum communication probability and I believe it may return misleading results in some cases.

If I combine the heatmaps in the same fashion as the tutorial I noticed that the coloring of the middle condition didn't seem to match what I saw in the circle plots, it seemed to have a probability much closer to the other two conditions as expected. 

![example_1](https://user-images.githubusercontent.com/53752249/189386337-811e3cc0-9abe-480a-a119-3ceee921dd6d.png)

When taking a look at the individual condition's heatmaps I noticed that the legends showed different values/scaling for each condition, but when they were combined using `ComplexHeatmap::draw(ht[[1]] + ht[[2]] + ht[[3]], ht_gap = unit(0.5, 'cm'))` it took the legend of the first condition without altering the color grading of any heatmap.

_(First condition, from where the legend for the "combined" plots is taken)_
![example_2](https://user-images.githubusercontent.com/53752249/189386334-9f1aea4d-aed6-4502-8a71-a575ba6b4f14.png)

_(Second condition, the one with the lowest communication probability in terms of order of magnitude)_ 
![example_3](https://user-images.githubusercontent.com/53752249/189386328-8759462c-7fc9-4aaa-8345-4c7a9f10e36f.png)
 
_(Last condition, comm. prob. a bit higher that in the First one)_
![example_4](https://user-images.githubusercontent.com/53752249/189386322-f9b8d3db-3c66-48af-9a77-5419df46e93c.png)

I've taking a look at the source code of the function for a time and as I'm not a well-seasoned programmer I find it a bit difficult to try to understand where I could make the necessary changes to 'scale' the probabilities myself for a correct comparison; or I don't know if its an issue coming from the `ComplexHeatmap` package.

Nonetheless, this issue was to ask if there's any way that I may be missing to circumvent this issue that you know of!  

I believe it's an important thing so I'll keep on trying to modify the source code (somewhat) by myself.

Thanks in advance~!

**Comment by ManuelMoradiellos** [comment]
Sorry for the late reply!

Thanks for the suggestion; I ended up doing a super draft-y function to create the heatmaps using the max scale value from my networks as you commented! Although they don't look as good as the default ones coming from here...

I really like this package but I can't get my head around why in most (all?) of the proposed plots for comparing datasets/experimental conditions there's no mention of this issue as it is a key point when contrasting results accurately

**Comment by hermioneallen** [comment]
Hi,

I'm having the same issue with scales in my heatmaps when comparing two datasets in a merged cellchat object. As mentioned in the previous messages,I want to make sure both heatmaps are plotted using the same scale so that they're directly comparable.

Not only are the parameters for the communication probability different on each heatmap, but so are the values showing the cumulative interaction strength in each cluster (both x and y axes):

![image](https://github.com/sqjin/CellChat/assets/44875003/b5c5632a-87b0-47c5-85c0-931b287ffab2)

I really tried to look through the netVisual_heatmap function to work out how to get the heatmaps to plot all 3 on the same scale but I couldn't work out how to do it! I found that using  `ht[[2]]@matrix_color_mapping@levels <- ht[[1]]@matrix_color_mapping@levels` would change the grid scale, but I can't for the life of me work out how to change the cumulative bar chart aspect! 

If anyone can share with me the code for a work around for this I would be so grateful - the way the netvisual_heatmap function interacts with complexheatmap for plotting is really complex and beyond my coding skills. 

@ManuelMoradiellos does your function using the max scale values fix all of the scales on the heatmap?
