### ISSUE TITLE
counts vs. normalized counts

### ISSUE THREAD

**Issue by s849** [sqjin/CellChat#54]
Hi,

I am wondering what is the advantage to use counts vs. normalized counts? 

What I did is: split my integrated object in Seurat into condition 1 and condition 2. I then followed your suggestion to get data from Seurat using GetAssay data. When I analyzed the matrix from each condition separately, I get what appears to be a counts matrix, even when I said assay "RNA" and slot "data". I did this:

Combined object is: Combined
Combined1 <- SubsetData(Combined, subset.name = "condition1", accept.value = "condition1") 

GetAssayData(Combined1, assay = "RNA", slot = "data") --- gives me counts matrix, not normalized.
Combined1@assays$RNA@data --- this also gives me counts matrix, not normalized.

What I did then was to use your function (normalizeData) to normalize the data for each object (combined1 and combined2). For my learning, I ran both count and normalized data for each condition separately and I get similar results, but I get a bit different results when I compare both with CellChat, especially in the information flow. 

Do you have any advice? What is the best practice?

Thank you

**Comment by sqjin** [comment]
Hi @s849 , we recommend the normalized data (library size + log(x+1)) as input of CellChat because the scale of gene expression is comparable after normalization. You can check whether you data is normalized by looking at the distribution of gene expression. The majority of genes should have maximum expression around 5.
