### ISSUE TITLE
rankNet results

### ISSUE THREAD

**Issue by jv-20** [sqjin/CellChat#63]
Hi Suoqin,

I have few quick questions. I am comparing two datasets (both have same cell types differ in disease). I followed your tutorial on comparison of datasets. I would appreciate your help with interpreting the figure generated from rankNet function. The code I used to generate the figure is `rankNet(cellchat_merged, mode = "comparison") `

1.What do the different colors mean? Those pathways names that are highlighted in black color are the ones that are equally important in two datasets. What do the red and green colored text mean?

2. What do the varying bar size mean? In my results, I see varying bar sizes for both the datasets. Those pathways with varying bar sizes some have pathway names highlighted in red, some in black and some in blue.

3. Where can I access the results from this function. 

4. What threshold is applied to show the pathways 

5. Likewise, what threshold is applied for the pathways shown in the river plot.

Thank you in advance. Thanks again for developing this tool. It is quite helpful for us.

**Comment by sqjin** [comment]
Hi @jv-20 , please see my comments below. 

1. Black colors mean equally important, one color like red means the enriched pathways in the first condition, and the other color like blue means the enriched pathways in the second condition. From the bar size, you can also make a judgement if the difference is large.

2. Bar size represents the information flow, which is computed by summarizing all the communication probability in that signaling pathway. 

3.  Since such function mainly aims to produce an intuitive visualization, we thus do not export the specific values. I can try to add such optional later this weekend. You can also get the information flow of certain pathway by using `apply(object@netP$prob, 3, sum)`

4/5. Both threshold are indicated in the documentation of functions. rankNet apply the threshold of p-values. For the threshold of river plot, please also check the Methods section of our preprint.

**Comment by jv-20** [comment]
Thank you so much Suoqin for the reply to my questions. The option you mentioned for query 3 would be nice, if possible. Thanks again 

Kind regards

**Comment by jv-20** [comment]
Hi Suoqin,

When I run the following code,  `rankNet(cellchat_merge_CDI_HC,` mode = `"comparison")` I get a warning message like below. Would you have any insights on this? Thank you 
Warning message:
Vectorized input to `element_text()` is not officially supported.
Results may be unexpected or may change in future versions of ggplot2.

**Comment by jv-20** [comment]
Hi Suoqin,

When I run the following code, rankNet(cellchat_merged_object, mode = "comparison") I get a warning message like below. Would you have any insights on this? Thank you
Warning message:
Vectorized input to element_text() is not officially supported.
Results may be unexpected or may change in future versions of ggplot2.

**Comment by sqjin** [comment]
Hi @jv-20 , Please just ignore the warning. I google it and it seems that no better solution for now. This is just used to color the text and thus will not affect the results. BTW, I just updated the rankNet function for better presenting the data and allowing for returning the data.frame.

**Comment by jv-20** [comment]
Hi @sqjin,

That's awesome, many thanks for that, you are very good. 

I tried to extract the results using `df=rankNet(cellchat_merged,mode = "comparison")` & then iuse `df$data` to store the results. 
1. Is this correct way to extract results for the data underlying rankNet figure?
2. A question on interpretation of the rankNet results. Please find the table below. In my results pathways 1 & 3 are highlighted in red; pathways 2 & 4 are highlighted in black and pathway 5 in green. The trouble I am having is how to interpret them. For example Pathways 3 & 4 have similar values in contribution.scaled column but are highlighted in two different colors. Would appreciate thoughts / insights on how to interpret them. Also, is there a way to apply a cutoff? Thank you 

![image](https://user-images.githubusercontent.com/68548237/96603818-4f7b6200-12ec-11eb-8e40-8242047bd49e.png)

**Comment by sqjin** [comment]
Hi @jv-20 , in the updated `rankNet` function, we provide a parameter called "return.data" to return the data if you set it to be TRUE. 

The pathways are categorized based on their relative contribution instead of the contribution.scale.  Yes, you can use the parameter called `tol` to apply a different cutoff.  Please check the documentation of the updated function. We made several improvements.

**Comment by jv-20** [comment]
Hi @sqjin , many thanks for that. I will look it  up. Thanks a lot
