### ISSUE TITLE
Interpreting communication probability values

### ISSUE THREAD

**Issue by dn-ra** [sqjin/CellChat#636]
Hi,

Thanks for writing and maintaining this useful tool.

I am having some trouble interpreting the communication probability values output by the package.

My collaborator wanted me to examine interactions between T cells and DCs in an experiment. I produced bubble plots using the `netVisual_bubble()` function and got the below plot:
![Screenshot 2023-06-13 at 11 45 32 am](https://github.com/sqjin/CellChat/assets/47837238/442aabde-1d9c-42b5-9c13-956f398a1ed2)

The collaborator then wanted to focus on the CD28 pathways, so I re-plotted without those paths and got the below:
![image](https://github.com/sqjin/CellChat/assets/47837238/86fdceae-65b3-4dd8-818d-74e76c48b5a4)

The key thing to point out is that for CD86-CD28, the colour label changes from blue/green (min probability) to red (high probability) across the plots. That's happening because the high probability MHC interactions are being removed, so the dynamic range of probability values is squished down.

But when I pull out the actual probability of CD86-CD28 in this dataset I get these values:
```, , CD86_CD28

      cDC1 cDC2 MoDCs pDC          T0          T1
cDC1     0    0     0   0 0.009205685 0.040756793
cDC2     0    0     0   0 0.002086346 0.009470208
MoDCs    0    0     0   0 0.001661002 0.007550906
pDC      0    0     0   0 0.000000000 0.000000000
T0       0    0     0   0 0.000000000 0.000000000
T1       0    0     0   0 0.000000000 0.000000000
```
which are quite low! So having a high communication probability as shown on the plot doesn't make much sense.

But when I look at the entire range of communication probability values from the entire analysis I get a histogram like this:
![image](https://github.com/sqjin/CellChat/assets/47837238/075a8ec9-45a2-460c-a598-ca834becf673)

So there are no very high probabilities. How, then, should I interpret the communication probabilities that are output when the probabilities never pass 0.30? What range should I be looking at to infer high-confidence interactions? Can I infer that there is communication happening at a probability of 0.04 or is likely to be a false discovery? I note that the p-values are significant for the plots above so I'm also wondering how I use commun.prob and p-value to interpret the plots in conjunction.

I'll be grateful for you advice.

**Comment by htejedam** [comment]
I was wondering something similar. Since many interactions seem to have very low probability. I guess this is the reason why they chose to put in the figure's key/legends a range from 0 to max in both the paper and the tutorials.

After reading the paper, in the methods section they mention: (https://www.nature.com/articles/s41467-021-21246-9)
**The communication probability here only represents the interaction strength and is not exactly a probability.** 
And I believe, these are the values plotted. What I did to confirm it was to check the gene expression in the cells of interest. In this way you can "double check". If you have spatial data, could be even better to see whether these cells are close or not.

**Comment by dn-ra** [comment]
Thank you! Great advice. I had forgotten about that part in the paper.
