### ISSUE TITLE
svglite only supports one page

### ISSUE THREAD

**Issue by JingleW** [sqjin/CellChat#66]
I tried CellChat for my own data. 
When I ran netVisual_aggregate, it reported an error in plot.new(): svglite only supports one page. 
And when I ran netVisual_signalingRole, it reported an error in grid.newpage(): svglite only supports one page. 
Could any please help to fix this problem?
Thank you.

**Comment by JingleW** [comment]
Furthermore, when I tried different values for the vertex.receiver, for example, vertex.receiver = seq(1,20) (there were 20 cell types of my data), running netVisual_aggregate reported an error in seq.default(space.v, 0, by = -space.v/(m1 - m - 1)) :  wrong sign in 'by' argument.

**Comment by sqjin** [comment]
Hi @JingleW , First, you cannot set vertex.receiver = seq(1,20) if you only have 20 clusters. You should use a small number of clusters. vertex.receiver means the cell clusters you want to show as a target in the first part of the plot. 

When running netVisual_aggregate and netVisual_signalingRole, it is surprising that you encounter the issue "svglite only supports one page"  because this is a very small plot. Have you tried to save the plot as follows:
  svglite(file = paste0(pathways.show[i], "_aggregate.svg"), width = 7, height = 5)
  netVisual_aggregate(cellchat, signaling = pathways.show[i],  vertex.receiver = vertex.receiver, vertex.size = groupSize)
  dev.off()

  grDevices::pdf(file = paste0("netImportance",pathways.show[i],".pdf"))
  netVisual_signalingRole(cellchat, pathways.show[i], slot.name = "netP")
  dev.off()

**Comment by JingleW** [comment]
Thank you very much. The problems is solved when setting the vertex.receiver to a smaller number.
