### ISSUE TITLE
mouse gene symbols in CellChatDB.human$interaction table

### ISSUE THREAD

**Issue by SoloveyMaria** [sqjin/CellChat#67]
Dear authors,

I am trying to use the CellChatDB.human database for my analysis of human single cell data. I realised that in the CellChatDB.Human$interaction table, some the gene symbols for ligands ( "ligand" column) are mouse and not human (e.g. MGI:95936, H2-T9 etc). For now, I just checked the MHC-I pathway_name, so I am not sure, whether other pathways are affected as well. Do you think you could fix this issue?

Best,
Maria Solovey

**Comment by sqjin** [comment]
Hi @SoloveyMaria , I just fixed the gene symbol issues in the human database, and please re-install the package.

**Comment by SoloveyMaria** [comment]
Hi @sqjin thank you so much! It looks much better now!

I still yet have a little issue with the annotations. 
In the CellChatDB.human$interaction$ligand, I sometimes encounter annotations that are not gene symbols (e.g. "Activin AB"). This makes it tricky to match these ligand names to the gene symbols in the CellChatDB.human$geneInfo$Symbol column. 
I tried to extract the ligand names from the CellChatDB.human$interaction$interaction_name_2 
`CellChatDB.human$interaction$ligands <- gsub("[ - ].*","",CellChatDB.human$interaction$interaction_name_2)`
and look them up in the CellChatDB.human$geneInfo$Symbol. 
`CellChatDB.human$interaction$ligand_found <- CellChatDB.human$interaction$ligands %in% CellChatDB.human$geneInfo$Symbol`
By doing this, I see some genes symbols (e.g. FGF15 or FLT3L) that are not present in the CellChatDB.human$geneInfo$Symbol. They have also different names in the CellChatDB.human$interaction$ligand column (e.g. FGF15 is called FGF19, and FLT3L is called FLT3LG).
`print("ligands not found in the annotation:")
CellChatDB.human$interaction[,c("ligand", "ligands")][!CellChatDB.human$interaction$ligand_found,]`

Would you have any chance to try to make it consistent? This would help me to use your database (which I find best to date!) in a more easy and straightforward way.

Thank you!

PS: I haven't checked if the receptors are fine...

**Comment by sqjin** [comment]
Hi @SoloveyMaria , the different names of gene symbol is because one is mouse gene and another is human gene. I can make some changes for all these similar issues, but I am afraid I am not available this week as several deadlines are approaching.  

However, for your questions, you do not need to do it as the way what you were doing. Since some ligands and receptors are multi-subunit complex, thus they are not gene names. You need to find the gene names in the CellChatDB.human$complex.  For a pair of ligand-receptor, you can find the gene set using the following codes: 
`    geneL <- unique(pairLR$ligand)
    geneR <- unique(pairLR$receptor)
    geneL <- extractGeneSubset(geneL, complex_input, geneInfo)
    geneR <- extractGeneSubset(geneR, complex_input, geneInfo)`
`#' Extract the gene name
#'
#' @param geneSet gene set
#' @param complex_input complex in CellChatDB databse
#' @param geneIfo official gene symbol
#'
#' @return
#' @importFrom dplyr select starts_with
#' @export
extractGeneSubset <- function(geneSet, complex_input, geneIfo) {
  complex <- geneSet[which(geneSet %in% geneIfo$Symbol == "FALSE")]
  geneSet <- intersect(geneSet, geneIfo$Symbol)
  complexsubunits <- dplyr::select(complex_input[match(complex, rownames(complex_input), nomatch=0),], starts_with("subunit"))
  complex <- intersect(complex, rownames(complexsubunits))
  complexsubunitsV <- unlist(complexsubunits)
  complexsubunitsV <- unique(complexsubunitsV[complexsubunitsV != ""])
  geneSet <- unique(c(geneSet, complexsubunitsV))
  return(geneSet)
}`

**Comment by SoloveyMaria** [comment]
Dear @sqjin , 

Thanks a lot for your reply and the code! I will try to do it like you suggest.

Best,
Maria
