### ISSUE TITLE
why   can  not find same  signaling  pathway 

### ISSUE THREAD

**Issue by tuqiang2014** [sqjin/CellChat#68]
dear  jin: 

I can not  find signaling  pathway  : `NF-kb ,  P53 ,MAPK, PPAR` ,in cellchatDB .  How can  I analyse these with  cellchat? 

thanks.

**Comment by sqjin** [comment]
Hi Yunlai @tuqiang2014 ,

The signaling pathways you mentioned can be activated by multiple sources and complicated mechanisms. For example, [Nfkb](https://www.genome.jp/kegg-bin/show_pathway?hsa04064) signaling is activated by a number of cytokine (e.g., TNF, IL1b) and other signaling molecule (e.g., EDN). Thus, I would not recommend performing cell-cell communication analysis for such pathways because it cannot tell you which ligands and receptors contribute to the communication. Instead, if you find the certain cytokine signaling is activated, then NFkb signaling is likely also activated.  BTW, CellChatDB can be also updated by users. Please check the [previous issue](#38 ). 

Best,
Suoqin
